# Generated by Django 5.2.12 on 2026-04-07 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Имя чемпиона')),
                ('title', models.CharField(max_length=200, verbose_name='Титул')),
                ('lore', models.TextField(verbose_name='История(Лор)')),
                ('role', models.CharField(choices=[('assasin', 'Уйбийца'), ('fighter', 'Воин'), ('mage', 'Маг'), ('marksman', 'Стрелок'), ('support', 'Поддержка'), ('tank', 'Танк')], default='fighter', max_length=20, verbose_name='Основная роль')),
                ('secondary_role', models.CharField(blank=True, choices=[('assasin', 'Уйбийца'), ('fighter', 'Воин'), ('mage', 'Маг'), ('marksman', 'Стрелок'), ('support', 'Поддержка'), ('tank', 'Танк')], max_length=20, null=True, verbose_name='Дополнительная роль')),
                ('fight_type', models.CharField(choices=[('melee', 'Ближний бой'), ('ranged', 'Дальний бой')], default='melee', max_length=15, verbose_name='Тип боя')),
                ('play_top', models.BooleanField(default=False, verbose_name='Топ')),
                ('play_jungle', models.BooleanField(default=False, verbose_name='Лес')),
                ('play_mid', models.BooleanField(default=False, verbose_name='Мид')),
                ('play_bot', models.BooleanField(default=False, verbose_name='Бот')),
                ('play_support', models.BooleanField(default=False, verbose_name='Саппорт')),
                ('hp', models.PositiveIntegerField(verbose_name='Здоровье')),
                ('mana', models.PositiveIntegerField(blank=True, null=True, verbose_name='Мана / Ресурс')),
                ('attack_damage', models.PositiveIntegerField(verbose_name='Сила атаки')),
                ('armour', models.PositiveIntegerField(verbose_name='Броня')),
                ('magic_resist', models.PositiveIntegerField(verbose_name='Сопротивление магии')),
                ('attack_range', models.PositiveIntegerField(default=125, verbose_name='Дальность атак')),
                ('movement_speed', models.PositiveIntegerField(default=330, verbose_name='Скорость передвижения')),
                ('image_main', models.ImageField(upload_to='champions/splashes/', verbose_name='Главный арт')),
                ('image_icon', models.ImageField(upload_to='champions/icons/', verbose_name='Иконка')),
                ('items_reasoning', models.TextField(blank=True, default='', verbose_name='Почему это лучшие предметы для него?')),
            ],
            options={
                'verbose_name': 'Чемпион',
                'verbose_name_plural': 'Чемпионы',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название артефакта')),
                ('image', models.ImageField(upload_to='items/', verbose_name='Изображение')),
                ('origin_story', models.TextField(help_text='Откуда взялся этот предмет в мире Рунтерры?', verbose_name='История артефакта')),
                ('stat_display', models.CharField(help_text='Например: +65 Силы атаки, +20% Скорости атаки', max_length=200, verbose_name='Характеристики')),
                ('unique_passive', models.TextField(verbose_name='Уникальный эффект(Пассивка)')),
            ],
            options={
                'verbose_name': 'Артефакт',
                'verbose_name_plural': 'Артефакты',
            },
        ),
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('P', 'Пассивное'), ('Q', 'Q'), ('W', 'W'), ('E', 'E'), ('R', 'Ульта')], max_length=1, verbose_name='Клавиша')),
                ('name', models.CharField(max_length=100, verbose_name='Название умения')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='champions/abilities/', verbose_name='Иконка умения')),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='LOLGuide.champion', verbose_name='Чемпион')),
            ],
            options={
                'verbose_name': 'Умение',
                'verbose_name_plural': 'Умения',
            },
        ),
        migrations.AddField(
            model_name='champion',
            name='item_slot_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot1_heroes', to='LOLGuide.item', verbose_name='Первый лучший предмет'),
        ),
        migrations.AddField(
            model_name='champion',
            name='item_slot_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot2_heroes', to='LOLGuide.item', verbose_name='Второй лучший предмет'),
        ),
        migrations.AddField(
            model_name='champion',
            name='item_slot_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot3_heroes', to='LOLGuide.item', verbose_name='Третий лучший предмет'),
        ),
    ]
