# Generated by Django 5.2.12 on 2026-04-07 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOLGuide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Noxus', 'Ноксус'), ('Demacia', 'Демасия'), ('Freljord', 'Фрельйорд'), ('Shurima', 'Шурима'), ('Ionia', 'Иония'), ('Targon', 'Таргон'), ('Ixtal', 'Ишталь'), ('Piltover', 'Пилтовер'), ('Zaun', 'Заун'), ('Bilgewater', 'Билджвотер'), ('Shadow Isles', 'Сумрачные острова'), ('The Void', 'Бездна'), ('Bandle City', 'Бандл Сити')], max_length=50, unique=True, verbose_name='Название')),
                ('tagline', models.CharField(help_text='Например: Сила превыше всего!', max_length=200, verbose_name='Слоган')),
                ('description', models.TextField(verbose_name='Лор региона')),
                ('emblem', models.ImageField(upload_to='regions/emblems/', verbose_name='Герб')),
                ('background', models.ImageField(upload_to='regions/backgrounds/', verbose_name='Фон страницы')),
                ('color', models.CharField(default='#C8AA6E', help_text='Например: #C8AA6E', max_length=7, verbose_name='Цвет региона')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.AddField(
            model_name='champion',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='champions', to='LOLGuide.region', verbose_name='Регион'),
        ),
    ]
