# Generated by Django 5.2.12 on 2026-04-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOLGuide', '0002_region_champion_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='JungleMonsters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('category', models.CharField(choices=[('common', 'Обычное существо'), ('boss', 'Босс')], max_length=10, verbose_name='Категория')),
                ('description', models.TextField(verbose_name='Описание/Лор')),
                ('image', models.ImageField(upload_to='monsters/', verbose_name='Изображение')),
                ('health', models.IntegerField(default=0, verbose_name='Здоровье')),
                ('gold_reward', models.IntegerField(default=0, verbose_name='Награда(золото)')),
                ('buff_description', models.TextField(blank=True, null=True, verbose_name='Описание баффа')),
            ],
            options={
                'verbose_name': 'Лесное существо',
                'verbose_name_plural': 'Лесные существа',
            },
        ),
    ]
