# Generated by Django 5.2.12 on 2026-04-08 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LOLGuide', '0003_junglemonsters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='unique_passive',
        ),
    ]
