# Generated by Django 5.2.12 on 2026-04-14 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOLGuide', '0004_remove_item_unique_passive'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='passive',
            field=models.TextField(blank=True, help_text='Какие пассивные умения есть у этого предмета?', null=True, verbose_name='Пассивные уменя'),
        ),
    ]
