# Generated by Django 5.2.12 on 2026-04-25 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOLGuide', '0005_item_passive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='stat_display',
            field=models.TextField(help_text='Например: +65 Силы атаки, +20% Скорости атаки', max_length=200, verbose_name='Характеристики'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='profiles/avatars/PFP_default.jpg', null=True, upload_to='profiles/avatars/', verbose_name='Аватар')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='О себе')),
                ('favourite_champion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LOLGuide.champion', verbose_name='Любимый чемпион')),
                ('favourite_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LOLGuide.region', verbose_name='Любимый регион')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
